apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
spec:
  selector:
    matchLabels:
      app: suricata
  template:
    metadata:
      labels:
        app: suricata
    spec:
      hostNetwork: true
      containers:
      - name: suricata
        image: ghcr.io/telekom-security/suricata:24.04.1
        env:
        - name: OINKCODE
          valueFrom:
            configMapKeyRef:
              name: tpot-config
              key: OINKCODE
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_NICE
            - NET_RAW
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /var/log/suricata
          subPath: suricata/log
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data