apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-certs
        image: alpine/openssl:latest
        command: ['sh', '-c', 'mkdir -p /etc/nginx/cert && openssl req -x509 -newkey rsa:4096 -keyout /etc/nginx/cert/nginx.key -out /etc/nginx/cert/nginx.crt -days 365 -nodes -subj "/C=US/ST=State/L=City/O=Organization/CN=tpot"']
        volumeMounts:
        - name: nginx-certs
          mountPath: /etc/nginx/cert
      - name: init-dirs
        image: busybox:1.35
        command: ['sh', '-c', 'mkdir -p /data/nginx/cert /data/nginx/conf /data/nginx/log /var/lib/nginx/logs /var/lib/nginx/tmp /etc/nginx && echo "admin:\$apr1\$X123456\$abcdefghijk123456789" > /etc/nginx/nginxpasswd && echo "logstash:\$apr1\$X123456\$abcdefghijk123456789" > /etc/nginx/lswebpasswd']
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: nginx
        - name: nginx-conf
          mountPath: /etc/nginx
        - name: nginx-logs
          mountPath: /var/lib/nginx/logs
      containers:
      - name: nginx
        image: ghcr.io/telekom-security/nginx:24.04.1
        env:
        - name: TPOT_OSTYPE
          value: "linux"
        ports:
        - containerPort: 64297
        - containerPort: 64294
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: false
          runAsUser: 100
          runAsGroup: 82
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: nginx
        - name: nginx-certs
          mountPath: /etc/nginx/cert
        - name: nginx-conf
          mountPath: /etc/nginx/nginxpasswd
          subPath: nginxpasswd
        - name: nginx-conf
          mountPath: /etc/nginx/lswebpasswd
          subPath: lswebpasswd
        - name: nginx-logs
          mountPath: /var/lib/nginx/logs
        - name: tmp-nginx
          mountPath: /var/tmp/nginx
        - name: run
          mountPath: /run
        - name: nginx-tmp
          mountPath: /var/lib/nginx/tmp
        readinessProbe:
          httpGet:
            path: /
            port: 64297
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
      - name: nginx-certs
        emptyDir: {}
      - name: nginx-conf
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}
      - name: tmp-nginx
        emptyDir: {}
      - name: run
        emptyDir: {}
      - name: nginx-tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: web
    port: 64297
    targetPort: 64297
    nodePort: 30297
  - name: logstash
    port: 64294
    targetPort: 64294
    nodePort: 30294