apiVersion: v1
kind: Service
metadata:
  name: tpot-web
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: web
    port: 64297
    targetPort: 64297
---
apiVersion: v1
kind: Service
metadata:
  name: tpot-honeypots
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: tpot
  ports:
  - name: ssh-cowrie
    port: 22
    targetPort: 22
  - name: telnet-cowrie
    port: 23
    targetPort: 23
  - name: ftp-dionaea
    port: 21
    targetPort: 21
  - name: mysql-dionaea
    port: 3306
    targetPort: 3306
  - name: elasticsearch-fake
    port: 9200
    targetPort: 9200