apiVersion: apps/v1
kind: Deployment
metadata:
  name: adbhoney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adbhoney
  template:
    metadata:
      labels:
        app: adbhoney
    spec:
      containers:
      - name: adbhoney
        image: ghcr.io/telekom-security/adbhoney:24.04.1
        ports:
        - containerPort: 5555
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
          runAsGroup: 2000
        volumeMounts:
        - name: data
          mountPath: /opt/adbhoney/log
          subPath: adbhoney/log
        - name: data
          mountPath: /opt/adbhoney/dl
          subPath: adbhoney/downloads
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
---
apiVersion: v1
kind: Service
metadata:
  name: adbhoney
spec:
  type: NodePort
  selector:
    app: adbhoney
  ports:
  - port: 5555
    targetPort: 5555
    nodePort: 30555