apiVersion: apps/v1
kind: Deployment
metadata:
  name: conpot-iec104
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conpot-iec104
  template:
    metadata:
      labels:
        app: conpot-iec104
    spec:
      containers:
      - name: conpot
        image: ghcr.io/telekom-security/conpot:24.04.1
        env:
        - name: CONPOT_CONFIG
          value: "/etc/conpot/conpot.cfg"
        - name: CONPOT_JSON_LOG
          value: "/var/log/conpot/conpot_IEC104.json"
        - name: CONPOT_LOG
          value: "/var/log/conpot/conpot_IEC104.log"
        - name: CONPOT_TEMPLATE
          value: "IEC104"
        - name: CONPOT_TMP
          value: "/tmp/conpot"
        ports:
        - containerPort: 161
          protocol: UDP
        - containerPort: 2404
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
          runAsGroup: 2000
        volumeMounts:
        - name: data
          mountPath: /var/log/conpot
          subPath: conpot/log
        - name: tmp
          mountPath: /tmp/conpot
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
      - name: tmp
        emptyDir:
          sizeLimit: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: conpot-iec104
spec:
  type: NodePort
  selector:
    app: conpot-iec104
  ports:
  - name: snmp
    port: 161
    targetPort: 161
    protocol: UDP
    nodePort: 30161
  - name: iec104
    port: 2404
    targetPort: 2404
    nodePort: 32404