apiVersion: apps/v1
kind: Deployment
metadata:
  name: dionaea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dionaea
  template:
    metadata:
      labels:
        app: dionaea
    spec:
      initContainers:
      - name: init-dirs
        image: busybox:1.35
        command: ['sh', '-c', 'mkdir -p /opt/dionaea/var/dionaea/roots/ftp /opt/dionaea/var/dionaea/roots/tftp /opt/dionaea/var/dionaea/roots/www /opt/dionaea/var/dionaea/roots/upnp /opt/dionaea/var/dionaea/binaries /opt/dionaea/var/log /opt/dionaea/var/dionaea/rtp /opt/dionaea/var/dionaea && touch /opt/dionaea/var/dionaea/dionaea.db && chown -R 2000:2000 /opt/dionaea/var/']
        volumeMounts:
        - name: dionaea-var
          mountPath: /opt/dionaea/var
      containers:
      - name: dionaea
        image: ghcr.io/telekom-security/dionaea:24.04.1
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 42
        - containerPort: 69
          protocol: UDP
        - containerPort: 81
        - containerPort: 135
        - containerPort: 445
        - containerPort: 1433
        - containerPort: 1723
        - containerPort: 1883
        - containerPort: 3306
        - containerPort: 27017
        stdin: true
        tty: true
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"
            cpu: "300m"
        securityContext:
          readOnlyRootFilesystem: false
          runAsUser: 2000
          runAsGroup: 2000
        volumeMounts:
        - name: dionaea-var
          mountPath: /opt/dionaea/var
        - name: data
          mountPath: /data
          subPath: dionaea
        readinessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
      - name: dionaea-var
        emptyDir:
          sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dionaea
spec:
  type: NodePort
  selector:
    app: dionaea
  ports:
  - name: ftp-data
    port: 20
    targetPort: 20
    nodePort: 30020
  - name: ftp
    port: 21
    targetPort: 21
    nodePort: 30021
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 30306
  - name: smb
    port: 445
    targetPort: 445
    nodePort: 30445