apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticpot
  template:
    metadata:
      labels:
        app: elasticpot
    spec:
      containers:
      - name: elasticpot
        image: ghcr.io/telekom-security/elasticpot:24.04.1
        ports:
        - containerPort: 9200
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
          runAsGroup: 2000
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: elasticpot
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticpot
spec:
  type: NodePort
  selector:
    app: elasticpot
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30920