apiVersion: apps/v1
kind: Deployment
metadata:
  name: heralding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heralding
  template:
    metadata:
      labels:
        app: heralding
    spec:
      containers:
      - name: heralding
        image: ghcr.io/telekom-security/heralding:24.04.1
        ports:
        - containerPort: 110
        - containerPort: 143
        - containerPort: 465
        - containerPort: 993
        - containerPort: 995
        - containerPort: 1080
        - containerPort: 5432
        - containerPort: 5900
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
          runAsGroup: 2000
        volumeMounts:
        - name: data
          mountPath: /var/log/heralding
          subPath: heralding/log
        - name: tmp
          mountPath: /tmp/heralding
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
      - name: tmp
        emptyDir:
          sizeLimit: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: heralding
spec:
  type: NodePort
  selector:
    app: heralding
  ports:
  - name: pop3
    port: 110
    targetPort: 110
    nodePort: 30110
  - name: imap
    port: 143
    targetPort: 143
    nodePort: 30143
  - name: smtps
    port: 465
    targetPort: 465
    nodePort: 30465
  - name: imaps
    port: 993
    targetPort: 993
    nodePort: 30993
  - name: pop3s
    port: 995
    targetPort: 995
    nodePort: 30995
  - name: socks5
    port: 1080
    targetPort: 1080
    nodePort: 31080
  - name: postgres
    port: 5432
    targetPort: 5432
    nodePort: 30432
  - name: vnc
    port: 5900
    targetPort: 5900
    nodePort: 30590