apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailoney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailoney
  template:
    metadata:
      labels:
        app: mailoney
    spec:
      containers:
      - name: mailoney
        image: ghcr.io/telekom-security/mailoney:24.04.1
        ports:
        - containerPort: 25
        stdin: true
        tty: true
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
          runAsGroup: 2000
        volumeMounts:
        - name: data
          mountPath: /opt/mailoney/logs
          subPath: mailoney/log
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
---
apiVersion: v1
kind: Service
metadata:
  name: mailoney
spec:
  type: NodePort
  selector:
    app: mailoney
  ports:
  - name: smtp
    port: 25
    targetPort: 25
    nodePort: 30025
  - name: submission
    port: 587
    targetPort: 25
    nodePort: 30587