apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpot
  template:
    metadata:
      labels:
        app: wordpot
    spec:
      containers:
      - name: wordpot
        image: ghcr.io/telekom-security/wordpot:24.04.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
          runAsGroup: 2000
        volumeMounts:
        - name: data
          mountPath: /opt/wordpot/logs
          subPath: wordpot/log
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
---
apiVersion: v1
kind: Service
metadata:
  name: wordpot
spec:
  type: NodePort
  selector:
    app: wordpot
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30808