apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: ghcr.io/telekom-security/elasticsearch:24.04.1
        env:
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: tpot-config
              key: ES_JAVA_OPTS
        - name: ES_TMPDIR
          value: "/tmp"
        ports:
        - containerPort: 9200
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - name: data
          mountPath: /data
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tpot-data
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200